---
- name: 'Resolve platform specific vars'
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'


- name: "Install certutil"
  ansible.builtin.apt:
    name: libnss3-tools
    state: present
  become: true
  when: mkcert_os == 'linux'


- name: 'Check if {{ mkcert_exe }} is installed'
  stat:
    path: '{{ mkcert_exe }}'
  register: mkcert_installed


- block:
  - name: 'Ensure {{ mkcert_install_dir }} exists'
    ansible.builtin.file:
      path: '{{ mkcert_install_dir }}'
      state: directory
      mode: 0755

  - name: 'Download {{ mkcert_url }} to {{ mkcert_exe }}'
    get_url:
      url: '{{ mkcert_url }}'
      dest: '{{ mkcert_exe }}'

  when: mkcert_installed.stat.exists is false


- name: 'Link {{ mkcert_link }} to {{ mkcert_exe }}'
  file:
    src: '{{ mkcert_exe }}'
    dest: '{{ mkcert_link }}'
    state: link
